//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sveit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sveit.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vacancy.
        /// </summary>
        internal static string AddVacancy {
            get {
                return ResourceManager.GetString("AddVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above {0} years old.
        /// </summary>
        internal static string AgeAbove {
            get {
                return ResourceManager.GetString("AgeAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between {0} and {1} years old.
        /// </summary>
        internal static string AgeBetween {
            get {
                return ResourceManager.GetString("AgeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to {0} years old.
        /// </summary>
        internal static string AgeUp {
            get {
                return ResourceManager.GetString("AgeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggressive.
        /// </summary>
        internal static string Aggressive {
            get {
                return ResourceManager.GetString("Aggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minute ago.
        /// </summary>
        internal static string AMinAgo {
            get {
                return ResourceManager.GetString("AMinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An hour ago.
        /// </summary>
        internal static string AnHourAgo {
            get {
                return ResourceManager.GetString("AnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies.
        /// </summary>
        internal static string Applies {
            get {
                return ResourceManager.GetString("Applies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register apply.
        /// </summary>
        internal static string ApplyFailed {
            get {
                return ResourceManager.GetString("ApplyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to approve apply.
        /// </summary>
        internal static string ApproveFailed {
            get {
                return ResourceManager.GetString("ApproveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to take photos..
        /// </summary>
        internal static string CameraDenied {
            get {
                return ResourceManager.GetString("CameraDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register comment.
        /// </summary>
        internal static string CommentFailed {
            get {
                return ResourceManager.GetString("CommentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        internal static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create team.
        /// </summary>
        internal static string CreateTeam {
            get {
                return ResourceManager.GetString("CreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decline apply.
        /// </summary>
        internal static string DeclineFailed {
            get {
                return ResourceManager.GetString("DeclineFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        internal static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete profile.
        /// </summary>
        internal static string DeleteProfileFailed {
            get {
                return ResourceManager.GetString("DeleteProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete team.
        /// </summary>
        internal static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete team.
        /// </summary>
        internal static string DeleteTeamFailed {
            get {
                return ResourceManager.GetString("DeleteTeamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        internal static string DPS {
            get {
                return ResourceManager.GetString("DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit apply.
        /// </summary>
        internal static string EditApply {
            get {
                return ResourceManager.GetString("EditApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        internal static string EditComment {
            get {
                return ResourceManager.GetString("EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string EditPlayer {
            get {
                return ResourceManager.GetString("EditPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit team.
        /// </summary>
        internal static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit vacancy.
        /// </summary>
        internal static string EditVacancy {
            get {
                return ResourceManager.GetString("EditVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        internal static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery not supported..
        /// </summary>
        internal static string GalleryNotSupported {
            get {
                return ResourceManager.GetString("GalleryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload image.
        /// </summary>
        internal static string ImageFailed {
            get {
                return ResourceManager.GetString("ImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields with invalid values, please check.
        /// </summary>
        internal static string InvalidValues {
            get {
                return ResourceManager.GetString("InvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave team.
        /// </summary>
        internal static string LeaveTeam {
            get {
                return ResourceManager.GetString("LeaveTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, verify credentials.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to logout.
        /// </summary>
        internal static string LogoutFailed {
            get {
                return ResourceManager.GetString("LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Age.
        /// </summary>
        internal static string MaxAge {
            get {
                return ResourceManager.GetString("MaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Age.
        /// </summary>
        internal static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string MinsAgo {
            get {
                return ResourceManager.GetString("MinsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New here? .
        /// </summary>
        internal static string NewHere {
            get {
                return ResourceManager.GetString("NewHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No age requirements.
        /// </summary>
        internal static string NoAgeRequirements {
            get {
                return ResourceManager.GetString("NoAgeRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts registered.
        /// </summary>
        internal static string NoContacts {
            get {
                return ResourceManager.GetString("NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requirements.
        /// </summary>
        internal static string NoRequirements {
            get {
                return ResourceManager.GetString("NoRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No specific skills required.
        /// </summary>
        internal static string NoSkillsRequired {
            get {
                return ResourceManager.GetString("NoSkillsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective.
        /// </summary>
        internal static string Objective {
            get {
                return ResourceManager.GetString("Objective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        internal static string OneDayAgo {
            get {
                return ResourceManager.GetString("OneDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month ago.
        /// </summary>
        internal static string OneMonthAgo {
            get {
                return ResourceManager.GetString("OneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One second ago.
        /// </summary>
        internal static string OneSecAgo {
            get {
                return ResourceManager.GetString("OneSecAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year ago.
        /// </summary>
        internal static string OneYearAgo {
            get {
                return ResourceManager.GetString("OneYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Denied.
        /// </summary>
        internal static string PermissionsDenied {
            get {
                return ResourceManager.GetString("PermissionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create account.
        /// </summary>
        internal static string PlayerFailed {
            get {
                return ResourceManager.GetString("PlayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove player from team.
        /// </summary>
        internal static string PlayerLeaveFailed {
            get {
                return ResourceManager.GetString("PlayerLeaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Role.
        /// </summary>
        internal static string PrimaryRole {
            get {
                return ResourceManager.GetString("PrimaryRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove player.
        /// </summary>
        internal static string RemovePlayer {
            get {
                return ResourceManager.GetString("RemovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        internal static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search comment.
        /// </summary>
        internal static string SearchComment {
            get {
                return ResourceManager.GetString("SearchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search game.
        /// </summary>
        internal static string SearchGame {
            get {
                return ResourceManager.GetString("SearchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search player.
        /// </summary>
        internal static string SearchPlayer {
            get {
                return ResourceManager.GetString("SearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search team.
        /// </summary>
        internal static string SearchTeam {
            get {
                return ResourceManager.GetString("SearchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search vacancy.
        /// </summary>
        internal static string SearchVacancy {
            get {
                return ResourceManager.GetString("SearchVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Role.
        /// </summary>
        internal static string SecondaryRole {
            get {
                return ResourceManager.GetString("SecondaryRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        internal static string SecsAgo {
            get {
                return ResourceManager.GetString("SecsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} skills required.
        /// </summary>
        internal static string SkillsRequired {
            get {
                return ResourceManager.GetString("SkillsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometime ago.
        /// </summary>
        internal static string SometimeAgo {
            get {
                return ResourceManager.GetString("SometimeAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store credencials.
        /// </summary>
        internal static string StoreCredencials {
            get {
                return ResourceManager.GetString("StoreCredencials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        internal static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create team.
        /// </summary>
        internal static string TeamFailed {
            get {
                return ResourceManager.GetString("TeamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to leave team.
        /// </summary>
        internal static string TeamLeaveFailed {
            get {
                return ResourceManager.GetString("TeamLeaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies.
        /// </summary>
        internal static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register vacancy.
        /// </summary>
        internal static string VacancyFailed {
            get {
                return ResourceManager.GetString("VacancyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        internal static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday at {0}.
        /// </summary>
        internal static string YesterdayAt {
            get {
                return ResourceManager.GetString("YesterdayAt", resourceCulture);
            }
        }
    }
}
